import type { ExecutiveDashboard } from "./types";

/**
 * Reference dataset for the executive home dashboard.
 *
 * Kept in one module so the API client can swap it for a real
 * `/metrics/executive-dashboard` response without touching the UI.
 */
export const executiveDashboard: ExecutiveDashboard = {
  lastRefreshedAt: "2026-07-28T06:15:00Z",
  source: "Clearinghouse + PM ledger sync",
  kpis: [
    {
      id: "total-charges",
      label: "Total charges",
      value: 24_860_000,
      format: "currency",
      deltaPct: 5.2,
      trend: "up",
      helper: "Gross charges posted, rolling 12 months",
      drillPath: "/revenue",
      drillHint: "Charges by facility, provider and CPT",
    },
    {
      id: "collections",
      label: "Collections",
      value: 18_420_500,
      format: "currency",
      deltaPct: 6.4,
      trend: "up",
      helper: "Cash posted against charges",
      drillPath: "/collections",
      drillHint: "Payment batches, posting lag and payer mix",
    },
    {
      id: "adjustments",
      label: "Adjustments",
      value: 4_912_000,
      format: "currency",
      deltaPct: -2.1,
      trend: "down",
      helper: "Contractual + administrative write-offs",
      drillPath: "/financial-analytics",
      drillHint: "Write-off reasons and contractual variance",
    },
    {
      id: "outstanding-balance",
      label: "Outstanding balance",
      value: 8_715_000,
      format: "currency",
      deltaPct: -3.4,
      trend: "down",
      helper: "Insurance + patient responsibility",
      drillPath: "/ar",
      drillHint: "Balance split by payer and aging bucket",
    },
    {
      id: "gross-collection-rate",
      label: "Gross collection rate",
      value: 74.1,
      format: "percent",
      deltaPct: 1.1,
      trend: "up",
      target: 76,
      helper: "Collections ÷ gross charges",
      drillPath: "/financial-analytics",
      drillHint: "GCR by payer, specialty and month",
    },
    {
      id: "net-collection-rate",
      label: "Net collection rate",
      value: 96.2,
      format: "percent",
      deltaPct: 0.8,
      trend: "up",
      target: 98,
      helper: "Collections ÷ allowed amount",
      drillPath: "/financial-analytics",
      drillHint: "NCR variance vs. contracted rates",
    },
    {
      id: "claims-submitted",
      label: "Claims submitted",
      value: 41_820,
      format: "number",
      deltaPct: 3.9,
      trend: "up",
      helper: "First-pass and re-submissions",
      drillPath: "/claims",
      drillHint: "Submission batches and clearinghouse status",
    },
    {
      id: "claims-paid",
      label: "Claims paid",
      value: 36_140,
      format: "number",
      deltaPct: 4.6,
      trend: "up",
      helper: "Fully or partially adjudicated",
      drillPath: "/claims",
      drillHint: "Paid claims with remittance detail",
    },
    {
      id: "claims-denied",
      label: "Claims denied",
      value: 2_634,
      format: "number",
      deltaPct: -6.8,
      trend: "down",
      helper: "Denied and awaiting appeal",
      drillPath: "/denials",
      drillHint: "Denials by CARC code and recoverability",
    },
    {
      id: "claims-pending",
      label: "Claims pending",
      value: 3_046,
      format: "number",
      deltaPct: 2.4,
      trend: "up",
      helper: "In payer adjudication",
      drillPath: "/claims",
      drillHint: "Pending claims by payer and days out",
    },
    {
      id: "current-ar",
      label: "Current A/R",
      value: 8_715_000,
      format: "currency",
      deltaPct: -3.1,
      trend: "down",
      helper: "Total open receivable",
      drillPath: "/ar",
      drillHint: "A/R waterfall and bucket movement",
    },
    {
      id: "days-in-ar",
      label: "Days in A/R",
      value: 34.2,
      format: "days",
      deltaPct: -8.1,
      trend: "down",
      target: 32,
      helper: "Target 32 days",
      drillPath: "/ar",
      drillHint: "Days in A/R by facility and payer",
    },
    {
      id: "denial-rate",
      label: "Denial rate",
      value: 6.3,
      format: "percent",
      deltaPct: -1.2,
      trend: "down",
      target: 5,
      helper: "Of all submitted claims",
      drillPath: "/denials",
      drillHint: "Denial rate trend and root causes",
    },
    {
      id: "cash-flow-forecast",
      label: "Cash flow forecast",
      value: 2_885_000,
      format: "currency",
      deltaPct: 2.7,
      trend: "up",
      helper: "Next 30 days, 90% confidence band",
      drillPath: "/forecast",
      drillHint: "Projection scenarios and confidence bands",
    },
  ],
  snapshot: [
    {
      id: "charges-today",
      label: "Charges posted today",
      value: 186_400,
      format: "currency",
      helper: "412 encounters captured",
      drillPath: "/billing",
    },
    {
      id: "payments-today",
      label: "Payments posted today",
      value: 148_900,
      format: "currency",
      helper: "9 remittance batches",
      drillPath: "/collections",
    },
    {
      id: "claims-today",
      label: "Claims submitted today",
      value: 318,
      format: "number",
      helper: "3 held for edits",
      drillPath: "/claims",
    },
    {
      id: "denials-today",
      label: "Denials received today",
      value: 24,
      format: "number",
      helper: "$41.2K at risk",
      drillPath: "/denials",
    },
    {
      id: "unbilled-today",
      label: "Unbilled encounters",
      value: 137,
      format: "number",
      helper: "48 awaiting provider signature",
      drillPath: "/billing",
    },
    {
      id: "clean-claim-today",
      label: "Clean claim rate today",
      value: 95.6,
      format: "percent",
      helper: "First-pass acceptance",
      drillPath: "/claims",
    },
  ],
  alerts: [
    {
      id: "alert-aetna",
      severity: "critical",
      title: "Aetna denials up 38% week over week",
      detail: "Prior-authorization CARC 197 spike concentrated in Lakeview Surgical orthopedics.",
      impact: 412_000,
      drillPath: "/denials",
    },
    {
      id: "alert-ar-120",
      severity: "critical",
      title: "$415K aged past 120 days",
      detail: "388 claims with no payer activity in 45 days across 3 facilities.",
      impact: 415_000,
      drillPath: "/ar",
    },
    {
      id: "alert-unsigned",
      severity: "warning",
      title: "48 encounters unsigned beyond 5 days",
      detail: "Charge capture delay is pushing an estimated $92K out of the current cycle.",
      impact: 92_000,
      drillPath: "/unsigned-encounters",
    },
    {
      id: "alert-credit",
      severity: "warning",
      title: "Credit balances require review",
      detail: "62 accounts hold refundable credits older than 30 days.",
      impact: 58_400,
      drillPath: "/patients",
    },
    {
      id: "alert-feed",
      severity: "info",
      title: "Westgate clearinghouse feed delayed 4 hours",
      detail: "Remittance files arrived late; posting caught up at 06:15.",
      impact: 0,
      drillPath: "/administration",
    },
  ],
  insights: [
    {
      id: "insight-denials",
      headline: "Working the top 3 denial codes could recover $1.1M this quarter",
      body: "CARC 197, 16 and 45 account for 61% of denied value, and 72% of similar denials were overturned on first appeal last quarter.",
      confidence: 0.82,
      drillPath: "/denials",
    },
    {
      id: "insight-ar",
      headline: "Days in A/R is trending to 31.4 by September",
      body: "Sustained payment velocity at UnitedHealthcare and Cigna is the primary driver; Medicaid remains the outlier at 48 days.",
      confidence: 0.74,
      drillPath: "/ar",
    },
    {
      id: "insight-cash",
      headline: "August cash is projected 2.7% above plan",
      body: "Charge volume growth at Northside offsets the seasonal dip in elective surgical revenue at Lakeview.",
      confidence: 0.68,
      drillPath: "/forecast",
    },
  ],
  collectionsTrend: [
    { month: "Aug", collected: 1_742_000, goal: 1_800_000 },
    { month: "Sep", collected: 1_868_000, goal: 1_850_000 },
    { month: "Oct", collected: 1_811_000, goal: 1_900_000 },
    { month: "Nov", collected: 2_042_000, goal: 1_950_000 },
    { month: "Dec", collected: 2_138_000, goal: 2_000_000 },
    { month: "Jan", collected: 2_090_000, goal: 2_100_000 },
    { month: "Feb", collected: 2_284_000, goal: 2_150_000 },
    { month: "Mar", collected: 2_431_000, goal: 2_250_000 },
  ],
  claimsTrend: [
    { month: "Aug", submitted: 4_820, paid: 4_120, denied: 342, pending: 358 },
    { month: "Sep", submitted: 5_010, paid: 4_338, denied: 320, pending: 352 },
    { month: "Oct", submitted: 4_940, paid: 4_205, denied: 361, pending: 374 },
    { month: "Nov", submitted: 5_260, paid: 4_602, denied: 318, pending: 340 },
    { month: "Dec", submitted: 5_480, paid: 4_798, denied: 306, pending: 376 },
    { month: "Jan", submitted: 5_190, paid: 4_512, denied: 331, pending: 347 },
    { month: "Feb", submitted: 5_540, paid: 4_876, denied: 297, pending: 367 },
    { month: "Mar", submitted: 5_580, paid: 4_929, denied: 289, pending: 362 },
  ],
  arTrend: [
    { month: "Aug", arBalance: 9_840_000, daysInAr: 41.8 },
    { month: "Sep", arBalance: 9_610_000, daysInAr: 40.2 },
    { month: "Oct", arBalance: 9_720_000, daysInAr: 39.6 },
    { month: "Nov", arBalance: 9_320_000, daysInAr: 38.1 },
    { month: "Dec", arBalance: 9_080_000, daysInAr: 36.9 },
    { month: "Jan", arBalance: 9_150_000, daysInAr: 36.4 },
    { month: "Feb", arBalance: 8_890_000, daysInAr: 35.1 },
    { month: "Mar", arBalance: 8_715_000, daysInAr: 34.2 },
  ],
  activity: [
    {
      id: "act-1",
      kind: "payment",
      title: "ERA batch posted — UnitedHealthcare",
      detail: "482 claims reconciled, 3 exceptions routed to Collections.",
      amount: 612_400,
      timestamp: "2026-07-28T05:48:00Z",
      drillPath: "/collections",
    },
    {
      id: "act-2",
      kind: "denial",
      title: "Denial cluster flagged — Aetna CARC 197",
      detail: "24 claims from Lakeview Surgical queued for appeal.",
      amount: 41_200,
      timestamp: "2026-07-28T04:22:00Z",
      drillPath: "/denials",
    },
    {
      id: "act-3",
      kind: "submission",
      title: "Claim batch transmitted to clearinghouse",
      detail: "318 claims accepted, 3 held for coding edits.",
      amount: 1_240_000,
      timestamp: "2026-07-28T02:05:00Z",
      drillPath: "/claims",
    },
    {
      id: "act-4",
      kind: "adjustment",
      title: "Contractual adjustments posted",
      detail: "Medicare fee-schedule update applied to 1,204 lines.",
      amount: 186_300,
      timestamp: "2026-07-27T22:40:00Z",
      drillPath: "/financial-analytics",
    },
    {
      id: "act-5",
      kind: "user",
      title: "Dana Meyers approved write-off policy change",
      detail: "Small-balance threshold raised to $15 for patient accounts.",
      timestamp: "2026-07-27T19:12:00Z",
      drillPath: "/administration",
    },
    {
      id: "act-6",
      kind: "payment",
      title: "Patient payment plan payments posted",
      detail: "96 auto-pay transactions cleared overnight.",
      amount: 38_900,
      timestamp: "2026-07-27T17:30:00Z",
      drillPath: "/patients",
    },
  ],
};
