import {
  Download,
  FileText,
  Play,
  Share2,
} from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { ReportLibraryRow } from "@/lib/api/reports-analytics-dashboard";
import { toast } from "sonner";

export function ReportViewerModal({
  report,
  open,
  onOpenChange,
}: {
  report: ReportLibraryRow | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  if (!report) return null;

  const handleDownload = () => {
    toast.success(`Downloading "${report.reportName}.${report.format.toLowerCase()}"`);
  };

  const handleGenerate = () => {
    toast.success(`Generating report "${report.reportName}"`);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl max-h-[85vh] overflow-y-auto p-6 rounded-2xl">
        <DialogHeader>
          <div className="flex items-center gap-3">
            <span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/15 text-primary">
              <FileText className="h-5 w-5" />
            </span>
            <div>
              <DialogTitle className="text-xl font-bold font-display tracking-tight flex items-center gap-2">
                {report.reportName}
                <Badge variant="outline" className="text-xs">
                  {report.format}
                </Badge>
              </DialogTitle>
              <DialogDescription className="text-xs text-muted-foreground">
                Category: {report.category} · Last Generated: {report.lastGenerated}
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="space-y-4 mt-2 text-xs">
          <div className="rounded-xl border border-border bg-muted/40 p-4 space-y-2">
            <h4 className="font-semibold uppercase tracking-wider text-muted-foreground text-[11px]">
              Report Specification & Metadata
            </h4>
            <p className="text-foreground text-sm leading-relaxed">{report.description}</p>
            <div className="grid gap-3 sm:grid-cols-3 pt-2 text-muted-foreground">
              <div>
                <span>Schedule Cadence: </span>
                <span className="font-semibold text-foreground">{report.schedule}</span>
              </div>
              <div>
                <span>Generated By: </span>
                <span className="font-semibold text-foreground">{report.generatedBy}</span>
              </div>
              <div>
                <span>Active Status: </span>
                <span className="font-semibold text-foreground">{report.status}</span>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-border bg-card p-4 space-y-3">
            <h4 className="font-semibold uppercase tracking-wider text-muted-foreground text-[11px]">
              Sample Preview Dataset (First 3 Rows)
            </h4>
            <div className="overflow-x-auto rounded-lg border border-border">
              <table className="w-full text-left text-xs">
                <thead className="bg-muted/50 font-semibold text-muted-foreground uppercase border-b border-border">
                  <tr>
                    <th className="py-2 px-3">Period / Entity</th>
                    <th className="py-2 px-3 text-right">Billed Charges</th>
                    <th className="py-2 px-3 text-right">Net Collections</th>
                    <th className="py-2 px-3 text-right">Denial Rate</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border/60 font-mono">
                  <tr>
                    <td className="py-2 px-3 font-sans font-medium">Main Campus Clinic</td>
                    <td className="py-2 px-3 text-right">$1,950,000</td>
                    <td className="py-2 px-3 text-right text-emerald-600 font-bold">$1,750,000</td>
                    <td className="py-2 px-3 text-right">3.8%</td>
                  </tr>
                  <tr>
                    <td className="py-2 px-3 font-sans font-medium">North Annex Orthopedics</td>
                    <td className="py-2 px-3 text-right">$2,010,000</td>
                    <td className="py-2 px-3 text-right text-emerald-600 font-bold">$1,820,000</td>
                    <td className="py-2 px-3 text-right">4.1%</td>
                  </tr>
                  <tr>
                    <td className="py-2 px-3 font-sans font-medium">Ambulatory Care Suite</td>
                    <td className="py-2 px-3 text-right">$2,150,000</td>
                    <td className="py-2 px-3 text-right text-emerald-600 font-bold">$1,940,000</td>
                    <td className="py-2 px-3 text-right">3.5%</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          <div className="flex items-center justify-end gap-2 pt-3 border-t border-border/50">
            <Button variant="outline" className="h-9 text-xs rounded-xl gap-1.5" onClick={handleGenerate}>
              <Play className="h-3.5 w-3.5" />
              Re-run Report
            </Button>
            <Button className="h-9 text-xs rounded-xl gap-1.5 font-semibold" onClick={handleDownload}>
              <Download className="h-3.5 w-3.5" />
              Export {report.format}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
