import { useMemo, useState } from "react";
import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  CalendarClock,
  Download,
  Edit,
  Eye,
  FileText,
  Filter,
  Play,
  Plus,
  Search,
  Trash2,
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ExportButton } from "@/components/common/ExportButton";
import type { ReportLibraryRow } from "@/lib/api/reports-analytics-dashboard";
import { ScheduleReportModal } from "@/components/dashboard/ScheduleReportModal";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

type SortField =
  | "reportName"
  | "category"
  | "lastGenerated"
  | "generatedBy"
  | "schedule"
  | "format"
  | "status";

type SortDirection = "asc" | "desc";

export function ReportsLibraryTable({
  rows,
  selectedCategory,
  onViewReport,
}: {
  rows: ReportLibraryRow[];
  selectedCategory: string | null;
  onViewReport?: (row: ReportLibraryRow) => void;
}) {
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("all");
  const [formatFilter, setFormatFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  const [sortField, setSortField] = useState<SortField>("reportName");
  const [sortDir, setSortDir] = useState<SortDirection>("asc");

  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const activeCategory = selectedCategory ?? (categoryFilter === "all" ? null : categoryFilter);

  const filtered = useMemo(() => {
    const s = search.trim().toLowerCase();

    return rows.filter((row) => {
      const matchGlobal =
        !s ||
        row.reportName.toLowerCase().includes(s) ||
        row.description.toLowerCase().includes(s) ||
        row.generatedBy.toLowerCase().includes(s);

      const matchCat = !activeCategory || row.category === activeCategory;
      const matchFmt = formatFilter === "all" || row.format === formatFilter;
      const matchStatus = statusFilter === "all" || row.status === statusFilter;

      return matchGlobal && matchCat && matchFmt && matchStatus;
    });
  }, [rows, search, activeCategory, formatFilter, statusFilter]);

  const sorted = useMemo(() => {
    return [...filtered].sort((a, b) => {
      let aVal = a[sortField];
      let bVal = b[sortField];

      if (typeof aVal === "string") {
        aVal = aVal.toLowerCase();
        bVal = (bVal as string).toLowerCase();
      }

      if (aVal < bVal) return sortDir === "asc" ? -1 : 1;
      if (aVal > bVal) return sortDir === "asc" ? 1 : -1;
      return 0;
    });
  }, [filtered, sortField, sortDir]);

  const totalPages = Math.max(1, Math.ceil(sorted.length / pageSize));
  const currentPage = Math.min(page, totalPages);
  const paginated = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return sorted.slice(start, start + pageSize);
  }, [sorted, currentPage, pageSize]);

  const toggleSort = (field: SortField) => {
    if (sortField === field) {
      setSortDir((prev) => (prev === "asc" ? "desc" : "asc"));
    } else {
      setSortField(field);
      setSortDir("asc");
    }
  };

  const renderSortIcon = (field: SortField) => {
    if (sortField !== field) return <ArrowUpDown className="h-3.5 w-3.5 opacity-40" />;
    return sortDir === "asc" ? (
      <ArrowUp className="h-3.5 w-3.5 text-primary" />
    ) : (
      <ArrowDown className="h-3.5 w-3.5 text-primary" />
    );
  };

  const handleGenerate = (row: ReportLibraryRow) => {
    toast.success(`Generating report: "${row.reportName}"`, {
      description: `Querying analytics engine. Output format: ${row.format}`,
    });
  };

  const handleDownload = (row: ReportLibraryRow) => {
    toast.success(`Downloading report: "${row.reportName}.${row.format.toLowerCase()}"`, {
      description: "File successfully saved to your downloads folder.",
    });
  };

  const [selectedReportForSchedule, setSelectedReportForSchedule] = useState<ReportLibraryRow | null>(null);
  const [scheduleOpen, setScheduleOpen] = useState(false);

  const handleSchedule = (row: ReportLibraryRow) => {
    setSelectedReportForSchedule(row);
    setScheduleOpen(true);
  };

  const handleDelete = (row: ReportLibraryRow) => {
    toast.error(`Report removed: "${row.reportName}"`);
  };

  const exportRows = useMemo(
    () =>
      sorted.map((r) => ({
        "Report Name": r.reportName,
        Category: r.category,
        Description: r.description,
        "Last Generated": r.lastGenerated,
        "Generated By": r.generatedBy,
        Schedule: r.schedule,
        Format: r.format,
        Status: r.status,
      })),
    [sorted],
  );

  return (
    <div className="space-y-4">
      {/* Controls Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-2.5 flex-1 min-w-[280px]">
          <div className="relative flex-1 min-w-[200px] max-w-sm">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setPage(1);
              }}
              placeholder="Search report name, description..."
              className="h-10 pl-9 rounded-xl"
            />
          </div>

          <Select
            value={formatFilter}
            onValueChange={(v) => {
              setFormatFilter(v);
              setPage(1);
            }}
          >
            <SelectTrigger className="h-10 w-[140px] rounded-xl">
              <SelectValue placeholder="Format" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Formats</SelectItem>
              <SelectItem value="PDF">PDF</SelectItem>
              <SelectItem value="Excel">Excel</SelectItem>
              <SelectItem value="CSV">CSV</SelectItem>
            </SelectContent>
          </Select>

          <Select
            value={statusFilter}
            onValueChange={(v) => {
              setStatusFilter(v);
              setPage(1);
            }}
          >
            <SelectTrigger className="h-10 w-[140px] rounded-xl">
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              <SelectItem value="Active">Active</SelectItem>
              <SelectItem value="Completed">Completed</SelectItem>
              <SelectItem value="Processing">Processing</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <div className="flex items-center gap-2">
          <ExportButton rows={exportRows} fileName="reports-library" className="h-10 rounded-xl" />
        </div>
      </div>

      {/* Grid Table */}
      <div className="overflow-x-auto rounded-xl border border-border bg-card shadow-e1">
        <table className="w-full text-left text-sm">
          <thead className="border-b border-border bg-muted/50 text-xs font-semibold text-muted-foreground uppercase tracking-wider">
            <tr>
              <th className="py-3.5 px-4 cursor-pointer hover:text-foreground" onClick={() => toggleSort("reportName")}>
                <div className="flex items-center gap-1.5">
                  Report Name {renderSortIcon("reportName")}
                </div>
              </th>
              <th className="py-3.5 px-4 cursor-pointer hover:text-foreground" onClick={() => toggleSort("category")}>
                <div className="flex items-center gap-1.5">
                  Category {renderSortIcon("category")}
                </div>
              </th>
              <th className="py-3.5 px-4 cursor-pointer hover:text-foreground" onClick={() => toggleSort("lastGenerated")}>
                <div className="flex items-center gap-1.5">
                  Last Generated {renderSortIcon("lastGenerated")}
                </div>
              </th>
              <th className="py-3.5 px-4 cursor-pointer hover:text-foreground" onClick={() => toggleSort("schedule")}>
                <div className="flex items-center gap-1.5">
                  Schedule {renderSortIcon("schedule")}
                </div>
              </th>
              <th className="py-3.5 px-3 text-center cursor-pointer hover:text-foreground" onClick={() => toggleSort("format")}>
                <div className="flex items-center justify-center gap-1.5">
                  Format {renderSortIcon("format")}
                </div>
              </th>
              <th className="py-3.5 px-3 text-center cursor-pointer hover:text-foreground" onClick={() => toggleSort("status")}>
                <div className="flex items-center justify-center gap-1.5">
                  Status {renderSortIcon("status")}
                </div>
              </th>
              <th className="py-3.5 px-4 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-border/60">
            {paginated.length === 0 ? (
              <tr>
                <td colSpan={7} className="py-12 text-center text-muted-foreground">
                  No reports match the current search or category filters.
                </td>
              </tr>
            ) : (
              paginated.map((row) => (
                <tr key={row.id} className="hover:bg-muted/40 transition-colors group">
                  <td className="py-3.5 px-4">
                    <div className="min-w-0">
                      <p className="font-semibold text-foreground group-hover:text-primary transition-colors cursor-pointer" onClick={() => onViewReport?.(row)}>
                        {row.reportName}
                      </p>
                      <p className="text-xs text-muted-foreground line-clamp-1">{row.description}</p>
                    </div>
                  </td>
                  <td className="py-3.5 px-4 text-xs">
                    <Badge variant="outline" className="font-normal">
                      {row.category}
                    </Badge>
                  </td>
                  <td className="py-3.5 px-4 text-xs">
                    <p className="font-medium text-foreground">{row.lastGenerated}</p>
                    <p className="text-[11px] text-muted-foreground">by {row.generatedBy}</p>
                  </td>
                  <td className="py-3.5 px-4 text-xs font-medium text-muted-foreground">{row.schedule}</td>
                  <td className="py-3.5 px-3 text-center">
                    <Badge
                      variant="secondary"
                      className={cn(
                        "text-[10px] font-bold",
                        row.format === "PDF"
                          ? "bg-rose-500/10 text-rose-600 border-rose-500/30"
                          : row.format === "Excel"
                          ? "bg-emerald-500/10 text-emerald-600 border-emerald-500/30"
                          : "bg-blue-500/10 text-blue-600 border-blue-500/30",
                      )}
                    >
                      {row.format}
                    </Badge>
                  </td>
                  <td className="py-3.5 px-3 text-center">
                    <Badge variant={row.status === "Active" ? "default" : "secondary"} className="text-[10px]">
                      {row.status}
                    </Badge>
                  </td>
                  <td className="py-3.5 px-4">
                    <div className="flex items-center justify-center gap-1">
                      <Button
                        variant="ghost"
                        size="sm"
                        title="View Report"
                        className="h-8 w-8 p-0 rounded-lg hover:text-primary"
                        onClick={() => onViewReport?.(row)}
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        title="Run & Generate"
                        className="h-8 w-8 p-0 rounded-lg hover:text-emerald-600"
                        onClick={() => handleGenerate(row)}
                      >
                        <Play className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        title="Download"
                        className="h-8 w-8 p-0 rounded-lg hover:text-blue-600"
                        onClick={() => handleDownload(row)}
                      >
                        <Download className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        title="Schedule"
                        className="h-8 w-8 p-0 rounded-lg hover:text-amber-600"
                        onClick={() => handleSchedule(row)}
                      >
                        <CalendarClock className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        title="Delete"
                        className="h-8 w-8 p-0 rounded-lg hover:text-destructive"
                        onClick={() => handleDelete(row)}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {/* Pagination Bar */}
      <div className="flex flex-wrap items-center justify-between gap-3 px-1 text-xs text-muted-foreground">
        <div>
          Showing {paginated.length > 0 ? (currentPage - 1) * pageSize + 1 : 0} to{" "}
          {Math.min(currentPage * pageSize, sorted.length)} of {sorted.length} reports
        </div>

        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2">
            <span>Rows per page:</span>
            <Select
              value={String(pageSize)}
              onValueChange={(v) => {
                setPageSize(Number(v));
                setPage(1);
              }}
            >
              <SelectTrigger className="h-8 w-16 rounded-lg text-xs">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="10">10</SelectItem>
                <SelectItem value="25">25</SelectItem>
                <SelectItem value="50">50</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-center gap-1">
            <Button
              variant="outline"
              size="sm"
              className="h-8 rounded-lg px-2.5 text-xs"
              disabled={currentPage <= 1}
              onClick={() => setPage((p) => p - 1)}
            >
              Previous
            </Button>
            <span className="px-2 font-medium">
              {currentPage} / {totalPages}
            </span>
            <Button
              variant="outline"
              size="sm"
              className="h-8 rounded-lg px-2.5 text-xs"
              disabled={currentPage >= totalPages}
              onClick={() => setPage((p) => p + 1)}
            >
              Next
            </Button>
          </div>
        </div>
      </div>

      <ScheduleReportModal
        report={selectedReportForSchedule}
        open={scheduleOpen}
        onOpenChange={setScheduleOpen}
      />
    </div>
  );
}
