/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsignedEncountersRouteImport } from './routes/unsigned-encounters'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProviderPerformanceRouteImport } from './routes/provider-performance'
import { Route as PredictiveAnalyticsRouteImport } from './routes/predictive-analytics'
import { Route as PersonalizationRouteImport } from './routes/personalization'
import { Route as PayersRouteImport } from './routes/payers'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatientAnalyticsRouteImport } from './routes/patient-analytics'
import { Route as OperationalDashboardRouteImport } from './routes/operational-dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MyRevenueRouteImport } from './routes/my-revenue'
import { Route as MyProductivityRouteImport } from './routes/my-productivity'
import { Route as MyEncountersRouteImport } from './routes/my-encounters'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KpiDashboardRouteImport } from './routes/kpi-dashboard'
import { Route as InsuranceDashboardRouteImport } from './routes/insurance-dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as FinancialAnalyticsRouteImport } from './routes/financial-analytics'
import { Route as DrilldownRouteImport } from './routes/drilldown'
import { Route as DenialsRouteImport } from './routes/denials'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ArRouteImport } from './routes/ar'
import { Route as AdministrationRouteImport } from './routes/administration'
import { Route as AccountSecurityRouteImport } from './routes/account-security'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsCategoryRouteImport } from './routes/reports_.$category'

const UnsignedEncountersRoute = UnsignedEncountersRouteImport.update({
  id: '/unsigned-encounters',
  path: '/unsigned-encounters',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderPerformanceRoute = ProviderPerformanceRouteImport.update({
  id: '/provider-performance',
  path: '/provider-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictiveAnalyticsRoute = PredictiveAnalyticsRouteImport.update({
  id: '/predictive-analytics',
  path: '/predictive-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizationRoute = PersonalizationRouteImport.update({
  id: '/personalization',
  path: '/personalization',
  getParentRoute: () => rootRouteImport,
} as any)
const PayersRoute = PayersRouteImport.update({
  id: '/payers',
  path: '/payers',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientAnalyticsRoute = PatientAnalyticsRouteImport.update({
  id: '/patient-analytics',
  path: '/patient-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalDashboardRoute = OperationalDashboardRouteImport.update({
  id: '/operational-dashboard',
  path: '/operational-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRevenueRoute = MyRevenueRouteImport.update({
  id: '/my-revenue',
  path: '/my-revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProductivityRoute = MyProductivityRouteImport.update({
  id: '/my-productivity',
  path: '/my-productivity',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEncountersRoute = MyEncountersRouteImport.update({
  id: '/my-encounters',
  path: '/my-encounters',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiDashboardRoute = KpiDashboardRouteImport.update({
  id: '/kpi-dashboard',
  path: '/kpi-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceDashboardRoute = InsuranceDashboardRouteImport.update({
  id: '/insurance-dashboard',
  path: '/insurance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialAnalyticsRoute = FinancialAnalyticsRouteImport.update({
  id: '/financial-analytics',
  path: '/financial-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DrilldownRoute = DrilldownRouteImport.update({
  id: '/drilldown',
  path: '/drilldown',
  getParentRoute: () => rootRouteImport,
} as any)
const DenialsRoute = DenialsRouteImport.update({
  id: '/denials',
  path: '/denials',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ArRoute = ArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrationRoute = AdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account-security',
  path: '/account-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCategoryRoute = ReportsCategoryRouteImport.update({
  id: '/reports_/$category',
  path: '/reports/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/ar': typeof ArRoute
  '/billing': typeof BillingRoute
  '/claims': typeof ClaimsRoute
  '/collections': typeof CollectionsRoute
  '/denials': typeof DenialsRoute
  '/drilldown': typeof DrilldownRoute
  '/financial-analytics': typeof FinancialAnalyticsRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/kpi-dashboard': typeof KpiDashboardRoute
  '/login': typeof LoginRoute
  '/my-encounters': typeof MyEncountersRoute
  '/my-productivity': typeof MyProductivityRoute
  '/my-revenue': typeof MyRevenueRoute
  '/notifications': typeof NotificationsRoute
  '/operational-dashboard': typeof OperationalDashboardRoute
  '/patient-analytics': typeof PatientAnalyticsRoute
  '/patients': typeof PatientsRoute
  '/payers': typeof PayersRoute
  '/personalization': typeof PersonalizationRoute
  '/predictive-analytics': typeof PredictiveAnalyticsRoute
  '/provider-performance': typeof ProviderPerformanceRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsigned-encounters': typeof UnsignedEncountersRoute
  '/reports/$category': typeof ReportsCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/ar': typeof ArRoute
  '/billing': typeof BillingRoute
  '/claims': typeof ClaimsRoute
  '/collections': typeof CollectionsRoute
  '/denials': typeof DenialsRoute
  '/drilldown': typeof DrilldownRoute
  '/financial-analytics': typeof FinancialAnalyticsRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/kpi-dashboard': typeof KpiDashboardRoute
  '/login': typeof LoginRoute
  '/my-encounters': typeof MyEncountersRoute
  '/my-productivity': typeof MyProductivityRoute
  '/my-revenue': typeof MyRevenueRoute
  '/notifications': typeof NotificationsRoute
  '/operational-dashboard': typeof OperationalDashboardRoute
  '/patient-analytics': typeof PatientAnalyticsRoute
  '/patients': typeof PatientsRoute
  '/payers': typeof PayersRoute
  '/personalization': typeof PersonalizationRoute
  '/predictive-analytics': typeof PredictiveAnalyticsRoute
  '/provider-performance': typeof ProviderPerformanceRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsigned-encounters': typeof UnsignedEncountersRoute
  '/reports/$category': typeof ReportsCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/account-security': typeof AccountSecurityRoute
  '/administration': typeof AdministrationRoute
  '/ar': typeof ArRoute
  '/billing': typeof BillingRoute
  '/claims': typeof ClaimsRoute
  '/collections': typeof CollectionsRoute
  '/denials': typeof DenialsRoute
  '/drilldown': typeof DrilldownRoute
  '/financial-analytics': typeof FinancialAnalyticsRoute
  '/forecast': typeof ForecastRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/insurance-dashboard': typeof InsuranceDashboardRoute
  '/kpi-dashboard': typeof KpiDashboardRoute
  '/login': typeof LoginRoute
  '/my-encounters': typeof MyEncountersRoute
  '/my-productivity': typeof MyProductivityRoute
  '/my-revenue': typeof MyRevenueRoute
  '/notifications': typeof NotificationsRoute
  '/operational-dashboard': typeof OperationalDashboardRoute
  '/patient-analytics': typeof PatientAnalyticsRoute
  '/patients': typeof PatientsRoute
  '/payers': typeof PayersRoute
  '/personalization': typeof PersonalizationRoute
  '/predictive-analytics': typeof PredictiveAnalyticsRoute
  '/provider-performance': typeof ProviderPerformanceRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revenue': typeof RevenueRoute
  '/session-expired': typeof SessionExpiredRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/unsigned-encounters': typeof UnsignedEncountersRoute
  '/reports_/$category': typeof ReportsCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/account-security'
    | '/administration'
    | '/ar'
    | '/billing'
    | '/claims'
    | '/collections'
    | '/denials'
    | '/drilldown'
    | '/financial-analytics'
    | '/forecast'
    | '/forgot-password'
    | '/insurance-dashboard'
    | '/kpi-dashboard'
    | '/login'
    | '/my-encounters'
    | '/my-productivity'
    | '/my-revenue'
    | '/notifications'
    | '/operational-dashboard'
    | '/patient-analytics'
    | '/patients'
    | '/payers'
    | '/personalization'
    | '/predictive-analytics'
    | '/provider-performance'
    | '/reports'
    | '/reset-password'
    | '/revenue'
    | '/session-expired'
    | '/settings'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/unsigned-encounters'
    | '/reports/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/account-security'
    | '/administration'
    | '/ar'
    | '/billing'
    | '/claims'
    | '/collections'
    | '/denials'
    | '/drilldown'
    | '/financial-analytics'
    | '/forecast'
    | '/forgot-password'
    | '/insurance-dashboard'
    | '/kpi-dashboard'
    | '/login'
    | '/my-encounters'
    | '/my-productivity'
    | '/my-revenue'
    | '/notifications'
    | '/operational-dashboard'
    | '/patient-analytics'
    | '/patients'
    | '/payers'
    | '/personalization'
    | '/predictive-analytics'
    | '/provider-performance'
    | '/reports'
    | '/reset-password'
    | '/revenue'
    | '/session-expired'
    | '/settings'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/unsigned-encounters'
    | '/reports/$category'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/account-security'
    | '/administration'
    | '/ar'
    | '/billing'
    | '/claims'
    | '/collections'
    | '/denials'
    | '/drilldown'
    | '/financial-analytics'
    | '/forecast'
    | '/forgot-password'
    | '/insurance-dashboard'
    | '/kpi-dashboard'
    | '/login'
    | '/my-encounters'
    | '/my-productivity'
    | '/my-revenue'
    | '/notifications'
    | '/operational-dashboard'
    | '/patient-analytics'
    | '/patients'
    | '/payers'
    | '/personalization'
    | '/predictive-analytics'
    | '/provider-performance'
    | '/reports'
    | '/reset-password'
    | '/revenue'
    | '/session-expired'
    | '/settings'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/unsigned-encounters'
    | '/reports_/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AdministrationRoute: typeof AdministrationRoute
  ArRoute: typeof ArRoute
  BillingRoute: typeof BillingRoute
  ClaimsRoute: typeof ClaimsRoute
  CollectionsRoute: typeof CollectionsRoute
  DenialsRoute: typeof DenialsRoute
  DrilldownRoute: typeof DrilldownRoute
  FinancialAnalyticsRoute: typeof FinancialAnalyticsRoute
  ForecastRoute: typeof ForecastRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InsuranceDashboardRoute: typeof InsuranceDashboardRoute
  KpiDashboardRoute: typeof KpiDashboardRoute
  LoginRoute: typeof LoginRoute
  MyEncountersRoute: typeof MyEncountersRoute
  MyProductivityRoute: typeof MyProductivityRoute
  MyRevenueRoute: typeof MyRevenueRoute
  NotificationsRoute: typeof NotificationsRoute
  OperationalDashboardRoute: typeof OperationalDashboardRoute
  PatientAnalyticsRoute: typeof PatientAnalyticsRoute
  PatientsRoute: typeof PatientsRoute
  PayersRoute: typeof PayersRoute
  PersonalizationRoute: typeof PersonalizationRoute
  PredictiveAnalyticsRoute: typeof PredictiveAnalyticsRoute
  ProviderPerformanceRoute: typeof ProviderPerformanceRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevenueRoute: typeof RevenueRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  UnsignedEncountersRoute: typeof UnsignedEncountersRoute
  ReportsCategoryRoute: typeof ReportsCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsigned-encounters': {
      id: '/unsigned-encounters'
      path: '/unsigned-encounters'
      fullPath: '/unsigned-encounters'
      preLoaderRoute: typeof UnsignedEncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-performance': {
      id: '/provider-performance'
      path: '/provider-performance'
      fullPath: '/provider-performance'
      preLoaderRoute: typeof ProviderPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictive-analytics': {
      id: '/predictive-analytics'
      path: '/predictive-analytics'
      fullPath: '/predictive-analytics'
      preLoaderRoute: typeof PredictiveAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalization': {
      id: '/personalization'
      path: '/personalization'
      fullPath: '/personalization'
      preLoaderRoute: typeof PersonalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payers': {
      id: '/payers'
      path: '/payers'
      fullPath: '/payers'
      preLoaderRoute: typeof PayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-analytics': {
      id: '/patient-analytics'
      path: '/patient-analytics'
      fullPath: '/patient-analytics'
      preLoaderRoute: typeof PatientAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-dashboard': {
      id: '/operational-dashboard'
      path: '/operational-dashboard'
      fullPath: '/operational-dashboard'
      preLoaderRoute: typeof OperationalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-revenue': {
      id: '/my-revenue'
      path: '/my-revenue'
      fullPath: '/my-revenue'
      preLoaderRoute: typeof MyRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-productivity': {
      id: '/my-productivity'
      path: '/my-productivity'
      fullPath: '/my-productivity'
      preLoaderRoute: typeof MyProductivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-encounters': {
      id: '/my-encounters'
      path: '/my-encounters'
      fullPath: '/my-encounters'
      preLoaderRoute: typeof MyEncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi-dashboard': {
      id: '/kpi-dashboard'
      path: '/kpi-dashboard'
      fullPath: '/kpi-dashboard'
      preLoaderRoute: typeof KpiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance-dashboard': {
      id: '/insurance-dashboard'
      path: '/insurance-dashboard'
      fullPath: '/insurance-dashboard'
      preLoaderRoute: typeof InsuranceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-analytics': {
      id: '/financial-analytics'
      path: '/financial-analytics'
      fullPath: '/financial-analytics'
      preLoaderRoute: typeof FinancialAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drilldown': {
      id: '/drilldown'
      path: '/drilldown'
      fullPath: '/drilldown'
      preLoaderRoute: typeof DrilldownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denials': {
      id: '/denials'
      path: '/denials'
      fullPath: '/denials'
      preLoaderRoute: typeof DenialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar': {
      id: '/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof ArRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administration': {
      id: '/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof AdministrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-security': {
      id: '/account-security'
      path: '/account-security'
      fullPath: '/account-security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports_/$category': {
      id: '/reports_/$category'
      path: '/reports/$category'
      fullPath: '/reports/$category'
      preLoaderRoute: typeof ReportsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AdministrationRoute: AdministrationRoute,
  ArRoute: ArRoute,
  BillingRoute: BillingRoute,
  ClaimsRoute: ClaimsRoute,
  CollectionsRoute: CollectionsRoute,
  DenialsRoute: DenialsRoute,
  DrilldownRoute: DrilldownRoute,
  FinancialAnalyticsRoute: FinancialAnalyticsRoute,
  ForecastRoute: ForecastRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InsuranceDashboardRoute: InsuranceDashboardRoute,
  KpiDashboardRoute: KpiDashboardRoute,
  LoginRoute: LoginRoute,
  MyEncountersRoute: MyEncountersRoute,
  MyProductivityRoute: MyProductivityRoute,
  MyRevenueRoute: MyRevenueRoute,
  NotificationsRoute: NotificationsRoute,
  OperationalDashboardRoute: OperationalDashboardRoute,
  PatientAnalyticsRoute: PatientAnalyticsRoute,
  PatientsRoute: PatientsRoute,
  PayersRoute: PayersRoute,
  PersonalizationRoute: PersonalizationRoute,
  PredictiveAnalyticsRoute: PredictiveAnalyticsRoute,
  ProviderPerformanceRoute: ProviderPerformanceRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RevenueRoute: RevenueRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  UnsignedEncountersRoute: UnsignedEncountersRoute,
  ReportsCategoryRoute: ReportsCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
